// pybind11 bindings: the only file that knows about Python and NumPy.
//
// It checks array shapes, allocates the output NumPy arrays, and passes raw
// pointers to the pure-C++ kernels in elasticity.cpp. The Python-facing return
// structure (dicts, tuples) is assembled in src/elasticity_utils.py, so this
// module stays a thin, flat interface.
#include <pybind11/numpy.h>
#include <pybind11/pybind11.h>

#include <stdexcept>
#include <string>

#include "build_info.hpp"  // generated by CMake: compiler + flags, for the benchmark
#include "elasticity.hpp"

namespace py = pybind11;

// Input array type. `c_style` requires row-major contiguous memory and
// `forcecast` allows conversion from other dtypes. A float64 C-contiguous array
// (what NumPy produces by default) passes straight through with no copy. A
// Fortran-ordered, sliced or float32 array is converted once into a temporary.
using InArray = py::array_t<double, py::array::c_style | py::array::forcecast>;
using OutArray = py::array_t<double>;

namespace {

std::size_t square_side(const InArray& a, const char* name) {
    if (a.ndim() != 2 || a.shape(0) != a.shape(1))
        throw std::invalid_argument(std::string(name) + " must be a square 2D array");
    return static_cast<std::size_t>(a.shape(0));
}

void require_side(const InArray& a, std::size_t N, const char* name) {
    if (square_side(a, name) != N)
        throw std::invalid_argument(std::string(name) + " has a different shape from exx");
}

OutArray new_grid(std::size_t N) {
    return OutArray({static_cast<py::ssize_t>(N), static_cast<py::ssize_t>(N)});
}

py::tuple build_greens_function(std::size_t grid_size, double mu, double nu) {
    OutArray Gxx = new_grid(grid_size), Gxy = new_grid(grid_size), Gyy = new_grid(grid_size);
    // mutable_data() is a pointer into the NumPy array's own buffer.
    double* pxx = Gxx.mutable_data();
    double* pxy = Gxy.mutable_data();
    double* pyy = Gyy.mutable_data();
    {
        // Release Python's global interpreter lock while pure C++ runs, so
        // other Python threads are not blocked. This is safe because nothing
        // in this block touches a Python object: only raw pointers.
        py::gil_scoped_release release;
        elasticity::build_greens_function(grid_size, mu, nu, pxx, pxy, pyy);
    }
    return py::make_tuple(Gxx, Gxy, Gyy);
}

py::tuple compute_strain_and_energy(const InArray& exx, const InArray& eyy, const InArray& exy,
                                    const InArray& Gxx, const InArray& Gxy, const InArray& Gyy,
                                    double mu, double nu) {
    const std::size_t N = square_side(exx, "exx");
    require_side(eyy, N, "eyy");
    require_side(exy, N, "exy");
    require_side(Gxx, N, "Gxx");
    require_side(Gxy, N, "Gxy");
    require_side(Gyy, N, "Gyy");

    OutArray eps_xx = new_grid(N), eps_yy = new_grid(N), eps_xy = new_grid(N);
    OutArray sig_xx = new_grid(N), sig_yy = new_grid(N), sig_xy = new_grid(N);
    OutArray energy_density = new_grid(N), ux = new_grid(N), uy = new_grid(N);

    const elasticity::StrainEnergyOutputs out{
        eps_xx.mutable_data(), eps_yy.mutable_data(), eps_xy.mutable_data(),
        sig_xx.mutable_data(), sig_yy.mutable_data(), sig_xy.mutable_data(),
        energy_density.mutable_data(), ux.mutable_data(), uy.mutable_data()};
    const double *pexx = exx.data(), *peyy = eyy.data(), *pexy = exy.data();
    const double *pGxx = Gxx.data(), *pGxy = Gxy.data(), *pGyy = Gyy.data();

    double total_energy;
    {
        py::gil_scoped_release release;
        total_energy = elasticity::compute_strain_and_energy(
            N, pexx, peyy, pexy, pGxx, pGxy, pGyy, mu, nu, out);
    }
    return py::make_tuple(eps_xx, eps_yy, eps_xy, sig_xx, sig_yy, sig_xy,
                          energy_density, total_energy, ux, uy);
}

}  // namespace

// PYBIND11_MODULE defines the function Python calls on `import _elasticity_cpp`.
// The first argument must match the module name set in CMakeLists.txt.
PYBIND11_MODULE(_elasticity_cpp, m) {
    m.doc() = "C++ kernels for src/elasticity_utils.py (see README, 'C++ kernel').";

    m.def("build_greens_function", &build_greens_function,
          py::arg("grid_size"), py::arg("mu"), py::arg("nu"),
          "Returns (Gxx, Gxy, Gyy). Called through elasticity_utils.build_greens_function.");

    m.def("compute_strain_and_energy", &compute_strain_and_energy,
          py::arg("exx"), py::arg("eyy"), py::arg("exy"),
          py::arg("Gxx"), py::arg("Gxy"), py::arg("Gyy"), py::arg("mu"), py::arg("nu"),
          "Returns a flat tuple (eps_xx, eps_yy, eps_xy, sig_xx, sig_yy, sig_xy, "
          "energy_density, total_energy, ux, uy). Called through "
          "elasticity_utils.compute_strain_and_energy.");

    m.def("build_info", [] {
        py::dict d;
        d["compiler"] = EK_COMPILER;
        d["build_type"] = EK_BUILD_TYPE;
        d["cxx_flags"] = EK_CXX_FLAGS;
        d["fft"] = EK_FFT;
        return d;
    }, "Compiler, build type and flags this module was built with.");
}
